name: CraftincBorderProtection
main: de.craftinc.borderprotection.Plugin
version: 0.9.5
author: ddidderr
website: http://www.craftinc.de/plugins/borderprotection


commands:
  cibp:
    description: Shows help for CraftInc BorderProtection

permissions:
  craftinc.borderprotection.set:
    default: false
    description: Allows to set the border for a world.
  craftinc.borderprotection.ignoreborders:
    default: false
    description: Allows to be everywhere on the map (ignoring the borders).
