#    Craft Inc. BorderProtection
#    Copyright (C) 2013  Paul Schulze, Tobias Ottenweller
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Craft Inc. BorderProtection
main: de.craftinc.borderprotection.Plugin
version: ${project.version}
authors: [ddidderr, mice_on_drugs]
website: http://www.craftinc.de/plugins/borderprotection


commands:
  cibp:
    description: Shows help for Craft Inc. BorderProtection

permissions:
  craftinc.borderprotection.set:
    default: op
    description: Allows to set the border for a world.
  craftinc.borderprotection.ignoreborders:
    default: op
    description: Allows to be everywhere on the map (ignoring the borders).
